-- ============================================================
-- Chạy trong Supabase SQL Editor (Dashboard → SQL Editor)
-- Bước 1: Chạy file này để tạo bảng và RLS
-- Bước 2: Chạy supabase-seed.sql để thêm dữ liệu mẫu (tùy chọn)
-- ============================================================

-- ---------- PROFILES (mở rộng auth.users) ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  address text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

-- ---------- ORDERS ----------
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  email text not null,
  total_amount numeric(10, 2) not null,
  status text default 'pending',
  raw_cart jsonb not null,
  created_at timestamptz default now()
);

alter table public.orders enable row level security;

create policy "Users can view own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Anyone can insert orders" on public.orders for insert with check (true);
create policy "Allow update orders" on public.orders for update using (true);

-- ---------- CATEGORIES ----------
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  image text,
  created_at timestamptz default now()
);

alter table public.categories enable row level security;

create policy "Allow all for categories" on public.categories for all using (true) with check (true);

-- ---------- PRODUCTS ----------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  price numeric(12, 2) not null,
  status text not null default 'in_stock',
  quantity int not null default 0,
  variants jsonb not null default '[]',
  main_image text not null,
  gallery jsonb not null default '[]',
  description_html text default '',
  external_links jsonb default '{}',
  created_at timestamptz default now()
);

alter table public.products enable row level security;

create policy "Allow all for products" on public.products for all using (true) with check (true);

-- ---------- SITE_SETTINGS (một dòng cấu hình) ----------
create table if not exists public.site_settings (
  id int primary key default 1 check (id = 1),
  site_name text default 'Shop Demo',
  logo_path text default '',
  main_visuals jsonb default '[{"id":"1","image":"/assets/upload/placeholder.svg","title":"Banner 1"}]',
  show_main_visual boolean default true,
  show_categories boolean default true,
  show_featured_products boolean default true,
  contact_email text default '',
  contact_instagram text default '',
  contact_tiktok text default '',
  updated_at timestamptz default now()
);

alter table public.site_settings enable row level security;

create policy "Allow all for site_settings" on public.site_settings for all using (true) with check (true);

-- Tạo dòng mặc định cho site_settings
insert into public.site_settings (id) values (1) on conflict (id) do nothing;
